apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::876091840844:role/NnekaFlaskDeployCBKubectlRole
      username: build   
    - groups:  
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::876091840844:role/eksctl-code-pipeline-nodegroup-ng-NodeInstanceRole-8SS73Y3LA2QE
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-10T14:47:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1305"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 1b8c5eec-87fe-4a88-9a57-d0f58d4da140
